In [1]:
import numpy as np

#Create B1
B1=np.array([[3,2]])
#take its transpose so that columns are vectors of B1
B1=B1.T


##### We notice that first column of the matrix B1 is the first vector of Basis B1 and so on

#similarly create B2
B2=np.array([[3,8],[1,-16]])
#note that we didnt take transpose this time

B2inB1=np.array([])
for b in B2: 
    #the reason we didnt take transpose this time is because we wanted to run it through a loop
    #Matrix M^-1 is obtained by writing basis vectors of B2 in B1 as columns of M
    #this for loop will calculate Basis vectors of B2 in B1
    
    
    #Here vectors of B2 are in standard basis (i,j,k,l) so to find its representation in B1, we simply take inverse 
    #of matrix B1 and multiply it by the vector.
    temp=(np.linalg.inv(B1) @ np.array(b).T)
    #append it in martix B2inB1
    B2inB1=np.append(B2inB1,temp, axis=0)

#take transpose of the matrix as stated above   
B2inB1=B2inB1.reshape(2,2).T

##### Thus our required M will just be inverse of B2inB1

M=np.linalg.inv(B2inB1).round(2)
M

LinAlgError: Last 2 dimensions of the array must be square

In [3]:
mat_V=np.array([2,3,1,-2]).reshape(2,2).T
mat_V

array([[ 2,  1],
       [ 3, -2]])

In [9]:
#v1 and v2 in terms of i and j
mat_V=np.array([2,3,1,-2]).reshape(2,2).T
#vectors of basis Bv in terms of v1 and v2
B_V1=np.array([2,-1])
B_V2=np.array([-2,5])
#converting Bv in terms of i and j from v1 and v2
M1=mat_V@B_V1
M2=mat_V@B_V2
#writing Bv as a matrix and taking its inverse
M=np.array([M1,M2]).T
M=np.linalg.inv(M)
print(M)

[[ 0.28571429  0.01785714]
 [ 0.14285714 -0.05357143]]


In [8]:
M1=np.linalg.inv(M)
M1

array([[  3.,   1.],
       [  8., -16.]])

In [6]:
B=np.array([[3],[2]])

In [10]:
out = M @ B
out

array([[0.89285714],
       [0.32142857]])