### Matrix Multiplication in Python

In [1]:
import numpy as np

In [14]:
A = np.array([[1,2],[2,3]])
B = np.array([[4,5],[6,9]])

In [4]:
A

array([[1, 2],
       [2, 3]])

In [5]:
B

array([[4, 5],
       [6, 9]])

In [15]:
C = A @ B

In [16]:
C

array([[16, 23],
       [26, 37]])