In [1]:
import numpy as np

In [12]:
B2=np.array([[3,8],[1,-16]])

In [13]:
Binv = np.linalg.inv(B2)

In [14]:
Binv

array([[ 0.28571429,  0.14285714],
       [ 0.01785714, -0.05357143]])

In [16]:
C = np.array([[3],[2]])

In [17]:
o = Binv @ C

In [18]:
o

array([[ 1.14285714],
       [-0.05357143]])

In [8]:
V = np.array([2,4,5,2]).T

In [9]:
V.shape

(4,)

In [5]:
V1 = V.T

In [6]:
V.shape

(4,)

In [10]:
o = B2 @ V

In [11]:
o

array([22, 30, 26, 22])